[book]
authors = ["zjp"]
language = "en"
multilingual = false
src = "src"
title = "ace"

[output.html]
[output.html.playground]
editable = true

[output.theme-ace]
theme-white = "github"
theme-dark = "solarized_dark"
